name: Pipeline1

on:
  push:
    branches:
      - master
    paths:
      - 'pipeline1.sh'
      - 'pipeline1_logfolder/*.log'
      - '.github/workflows/pipeline1.yml'

jobs:
  execute-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run the pipeline1 script
        run: |
          chmod +x ./pipeline1.sh
            bash ./pipeline1.sh
